
services:
  - type: web
    name: room-booking
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: daphne -p $PORT -b 0.0.0.0 room_booking.asgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: room-booking-db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
databases:
  - name: room-booking-db
    plan: free
