# Generated by Django 6.0.4 on 2026-04-22 11:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'อาคาร',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่ออุปกรณ์')),
                ('icon', models.CharField(blank=True, help_text='เช่น fa-wifi, fa-tv', max_length=50)),
            ],
            options={
                'verbose_name': 'มาสเตอร์อุปกรณ์',
                'verbose_name_plural': 'มาสเตอร์อุปกรณ์',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'ผู้ดูแลระบบ'), ('staff', 'เจ้าหน้าที่'), ('lecturer', 'อาจารย์'), ('student', 'นักศึกษา')], default='student', max_length=20)),
                ('faculty', models.CharField(blank=True, max_length=100, verbose_name='คณะ/หน่วยงาน')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ผู้ใช้งาน',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('room_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('available', 'ว่าง'), ('occupied', 'ถูกใช้งาน'), ('maintenance', 'ซ่อมบำรุง'), ('disabled', 'ปิดใช้งาน')], default='available', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='booking.building')),
            ],
            options={
                'verbose_name': 'ห้อง',
                'unique_together': {('building', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อกิจกรรม/วัตถุประสงค์')),
                ('attendees', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'รอยืนยัน'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('cancelled', 'ยกเลิก'), ('completed', 'เสร็จสิ้น'), ('no_show', 'ไม่มาใช้งาน')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('reminded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.room')),
            ],
            options={
                'verbose_name': 'การจองรายวัน',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200, verbose_name='ชื่อรายวิชา/กิจกรรม')),
                ('subject_code', models.CharField(blank=True, max_length=20, verbose_name='รหัสวิชา')),
                ('attendees', models.IntegerField(verbose_name='จำนวนนักศึกษา/ผู้เข้าร่วม')),
                ('day_of_week', models.IntegerField(choices=[(0, 'จันทร์'), (1, 'อังคาร'), (2, 'พุธ'), (3, 'พฤหัสบดี'), (4, 'ศุกร์'), (5, 'เสาร์'), (6, 'อาทิตย์')], verbose_name='วันในสัปดาห์')),
                ('start_time', models.TimeField(verbose_name='เวลาเริ่ม')),
                ('end_time', models.TimeField(verbose_name='เวลาสิ้นสุด')),
                ('term_start', models.DateField(verbose_name='วันเริ่มเทอม')),
                ('term_end', models.DateField(verbose_name='วันสิ้นสุดเทอม')),
                ('term_name', models.CharField(blank=True, max_length=50, verbose_name='ชื่อเทอม')),
                ('status', models.CharField(choices=[('active', 'ใช้งานอยู่'), ('cancelled', 'ยกเลิกแล้ว'), ('ended', 'หมดเทอมแล้ว')], default='active', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_term_bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_bookings', to='booking.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'การจองทั้งเทอม',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('booking_approved', 'การจองได้รับอนุมัติ'), ('booking_rejected', 'การจองถูกปฏิเสธ'), ('booking_reminder', 'เตือนก่อนใช้งาน'), ('booking_cancelled', 'การจองถูกยกเลิก'), ('term_approved', 'การจองทั้งเทอมได้รับอนุมัติ'), ('demand_alert', 'แจ้งเตือนความต้องการสูง'), ('system', 'ระบบ')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('term_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.termbooking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='booking.booking')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('term_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='booking.termbooking')),
            ],
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('hour', models.IntegerField()),
                ('predicted_demand', models.FloatField(help_text='0.0 – 1.0')),
                ('demand_level', models.CharField(choices=[('low', 'ต่ำ'), ('medium', 'ปานกลาง'), ('high', 'สูง'), ('urgent', 'เร่งด่วน')], default='low', max_length=10)),
                ('availability', models.CharField(choices=[('likely_available', '🟢 ยังว่าง'), ('recommended', '🟡 ควรจอง'), ('book_soon', '🟠 รีบจอง'), ('book_now', '🔴 ควรจองตอนนี้เลย')], default='likely_available', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('term_demand', models.FloatField(default=0.0)),
                ('dynamic_demand', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='booking.room')),
            ],
            options={
                'verbose_name': 'การพยากรณ์ความต้องการ',
                'ordering': ['forecast_date', 'hour'],
                'unique_together': {('room', 'forecast_date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='จำนวน')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.facility', verbose_name='อุปกรณ์')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_facilities', to='booking.room')),
            ],
            options={
                'verbose_name': 'อุปกรณ์ประจำห้อง',
                'unique_together': {('room', 'facility')},
            },
        ),
        migrations.CreateModel(
            name='RoomUsageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_bookings', models.IntegerField(default=0)),
                ('term_bookings', models.IntegerField(default=0)),
                ('dynamic_bookings', models.IntegerField(default=0)),
                ('utilization_rate', models.FloatField(default=0.0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='booking.room')),
            ],
            options={
                'unique_together': {('room', 'date')},
            },
        ),
    ]
