# Generated by Django 5.2.8 on 2026-03-10 13:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่ออาคาร')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='รหัสอาคาร')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'อาคาร',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'ผู้ดูแลระบบ'), ('staff', 'เจ้าหน้าที่'), ('lecturer', 'อาจารย์'), ('student', 'นักศึกษา')], default='student', max_length=20)),
                ('faculty', models.CharField(blank=True, max_length=100, verbose_name='คณะ/หน่วยงาน')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทร')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ผู้ใช้งาน',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อกิจกรรม/วัตถุประสงค์')),
                ('attendees', models.IntegerField(verbose_name='จำนวนผู้เข้าร่วม')),
                ('start_time', models.DateTimeField(verbose_name='เวลาเริ่ม')),
                ('end_time', models.DateTimeField(verbose_name='เวลาสิ้นสุด')),
                ('status', models.CharField(choices=[('pending', 'รอยืนยัน'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('cancelled', 'ยกเลิก'), ('completed', 'เสร็จสิ้น'), ('no_show', 'ไม่มาใช้งาน')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('chatbot', 'แชตบอท'), ('web', 'เว็บแอป'), ('admin', 'Admin')], default='web', max_length=20)),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'การจอง',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='booking.booking')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ประวัติการจอง',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, help_text='การจองที่เกิดขึ้นจาก Session นี้', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'เซสชันแชตบอท',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'ผู้ใช้'), ('bot', 'แชตบอท')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='booking.chatsession')),
            ],
            options={
                'verbose_name': 'ข้อความแชต',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('booking_approved', 'การจองได้รับอนุมัติ'), ('booking_rejected', 'การจองถูกปฏิเสธ'), ('booking_reminder', 'เตือนก่อนใช้งาน'), ('booking_cancelled', 'การจองถูกยกเลิก'), ('demand_alert', 'แจ้งเตือนความต้องการสูง'), ('system', 'ระบบ')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ชื่อห้อง')),
                ('floor', models.IntegerField(verbose_name='ชั้น')),
                ('capacity', models.IntegerField(verbose_name='ความจุ (คน)')),
                ('room_type', models.CharField(max_length=50, verbose_name='ประเภทห้อง')),
                ('status', models.CharField(choices=[('available', 'ว่าง'), ('occupied', 'ถูกใช้งาน'), ('maintenance', 'ซ่อมบำรุง'), ('disabled', 'ปิดใช้งาน')], default='available', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='booking.building')),
            ],
            options={
                'verbose_name': 'ห้อง',
                'unique_together': {('building', 'name')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.room'),
        ),
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่ออุปกรณ์')),
                ('quantity', models.IntegerField(default=1, verbose_name='จำนวน')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='booking.room')),
            ],
            options={
                'verbose_name': 'อุปกรณ์ในห้อง',
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(verbose_name='วันที่พยากรณ์')),
                ('hour', models.IntegerField(verbose_name='ชั่วโมง (0-23)')),
                ('predicted_demand', models.FloatField(verbose_name='ความต้องการที่คาดการณ์ (0-1)')),
                ('demand_level', models.CharField(choices=[('low', 'ต่ำ'), ('medium', 'ปานกลาง'), ('high', 'สูง')], default='low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='booking.room')),
            ],
            options={
                'verbose_name': 'การพยากรณ์ความต้องการ',
                'unique_together': {('room', 'forecast_date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='RoomUsageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('total_bookings', models.IntegerField(default=0, verbose_name='จำนวนการจองทั้งหมด')),
                ('completed', models.IntegerField(default=0, verbose_name='ใช้งานจริง')),
                ('no_show', models.IntegerField(default=0, verbose_name='ไม่มาใช้งาน')),
                ('cancelled', models.IntegerField(default=0, verbose_name='ยกเลิก')),
                ('utilization_rate', models.FloatField(default=0.0, verbose_name='อัตราการใช้งาน (%)')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='booking.room')),
            ],
            options={
                'verbose_name': 'สถิติห้อง',
                'unique_together': {('room', 'date')},
            },
        ),
    ]
