# Generated by Django 5.2.8 on 2026-03-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='demandforecast',
            options={'ordering': ['forecast_date', 'hour'], 'verbose_name': 'การพยากรณ์ความต้องการ'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='source',
        ),
        migrations.AddField(
            model_name='demandforecast',
            name='availability',
            field=models.CharField(choices=[('likely_available', '🟢 มีโอกาสว่างสูง'), ('likely_busy', '🟡 มีโอกาสแน่นปานกลาง'), ('likely_full', '🔴 มีโอกาสเต็ม')], default='likely_available', max_length=20, verbose_name='สถานะที่คาดการณ์'),
        ),
        migrations.AddField(
            model_name='demandforecast',
            name='confidence',
            field=models.FloatField(default=0.0, help_text='0-100 เปอร์เซ็นต์', verbose_name='ความมั่นใจของโมเดล (%)'),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='demand_level',
            field=models.CharField(choices=[('low', 'ต่ำ'), ('medium', 'ปานกลาง'), ('high', 'สูง')], default='low', max_length=10, verbose_name='ระดับความต้องการ'),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='predicted_demand',
            field=models.FloatField(help_text='0 = ไม่มีความต้องการเลย, 1 = ต้องการสูงสุด', verbose_name='ค่าความต้องการที่คาดการณ์ (0.0-1.0)'),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
