# Generated by Django 6.0.4 on 2026-05-01 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'รอยืนยัน'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('cancelled', 'ยกเลิก'), ('completed', 'เสร็จสิ้น'), ('no_show', 'ไม่มาใช้งาน'), ('checked_in', 'เช็คอินแล้ว')], default='pending', max_length=20),
        ),
    ]
