# Generated by Django 6.0.3 on 2026-03-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_chatsession_booking_remove_chatsession_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandforecast',
            name='predicted_demand',
            field=models.FloatField(help_text='0 = ไม่มีความต้องการเลย, 100 = ต้องการสูงสุด', verbose_name='ค่าความต้องการที่คาดการณ์ (0–100)'),
        ),
    ]
