# Generated by Django 6.0.4 on 2026-08-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_maintenanceblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='ชื่ออุปกรณ์'),
        ),
    ]
