# Generated by Django 6.0.3 on 2026-03-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_demandforecast_predicted_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='eminded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='hecked_in',
            field=models.BooleanField(default=False),
        ),
    ]
