# Generated by Django 6.0.3 on 2026-03-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_eminded_booking_hecked_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='eminded',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hecked_in',
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_in',
            field=models.BooleanField(default=False, verbose_name='Check-in แล้ว'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminded',
            field=models.BooleanField(default=False, verbose_name='แจ้งเตือนแล้ว'),
        ),
    ]
