# Generated by Django 6.0.3 on 2026-04-03 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_eminded_remove_booking_hecked_in_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'การจองรายวัน'},
        ),
        migrations.AddField(
            model_name='demandforecast',
            name='dynamic_demand',
            field=models.FloatField(default=0.0, help_text='ส่วนที่มาจาก Dynamic Booking (0-1)'),
        ),
        migrations.AddField(
            model_name='demandforecast',
            name='term_demand',
            field=models.FloatField(default=0.0, help_text='ส่วนที่มาจาก TermBooking (0-1)'),
        ),
        migrations.AddField(
            model_name='roomusagestat',
            name='dynamic_bookings',
            field=models.IntegerField(default=0, help_text='จำนวน Dynamic Booking'),
        ),
        migrations.AddField(
            model_name='roomusagestat',
            name='term_bookings',
            field=models.IntegerField(default=0, help_text='จำนวน slot จาก TermBooking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='attendees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reminded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='building',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='availability',
            field=models.CharField(choices=[('likely_available', '🟢 มีโอกาสว่างสูง'), ('likely_busy', '🟡 มีโอกาสแน่นปานกลาง'), ('likely_full', '🔴 มีโอกาสเต็ม')], default='likely_available', max_length=20),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='demand_level',
            field=models.CharField(choices=[('low', 'ต่ำ'), ('medium', 'ปานกลาง'), ('high', 'สูง')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='forecast_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='predicted_demand',
            field=models.FloatField(help_text='0.0 – 1.0'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_approved', 'การจองได้รับอนุมัติ'), ('booking_rejected', 'การจองถูกปฏิเสธ'), ('booking_reminder', 'เตือนก่อนใช้งาน'), ('booking_cancelled', 'การจองถูกยกเลิก'), ('term_approved', 'การจองทั้งเทอมได้รับอนุมัติ'), ('demand_alert', 'แจ้งเตือนความต้องการสูง'), ('system', 'ระบบ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roomfacility',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roomfacility',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='roomusagestat',
            name='cancelled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomusagestat',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomusagestat',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roomusagestat',
            name='no_show',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomusagestat',
            name='total_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomusagestat',
            name='utilization_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='TermBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200, verbose_name='ชื่อรายวิชา/กิจกรรม')),
                ('subject_code', models.CharField(blank=True, max_length=20, verbose_name='รหัสวิชา')),
                ('attendees', models.IntegerField(verbose_name='จำนวนนักศึกษา/ผู้เข้าร่วม')),
                ('day_of_week', models.IntegerField(choices=[(0, 'จันทร์'), (1, 'อังคาร'), (2, 'พุธ'), (3, 'พฤหัสบดี'), (4, 'ศุกร์'), (5, 'เสาร์'), (6, 'อาทิตย์')], verbose_name='วันในสัปดาห์')),
                ('start_time', models.TimeField(verbose_name='เวลาเริ่ม')),
                ('end_time', models.TimeField(verbose_name='เวลาสิ้นสุด')),
                ('term_start', models.DateField(verbose_name='วันเริ่มเทอม')),
                ('term_end', models.DateField(verbose_name='วันสิ้นสุดเทอม')),
                ('term_name', models.CharField(blank=True, help_text='เช่น ภาคเรียนที่ 1/2568', max_length=50, verbose_name='ชื่อเทอม')),
                ('status', models.CharField(choices=[('active', 'ใช้งานอยู่'), ('cancelled', 'ยกเลิกแล้ว'), ('ended', 'หมดเทอมแล้ว')], default='active', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_term_bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_bookings', to='booking.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'การจองทั้งเทอม',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='bookinglog',
            name='term_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='booking.termbooking'),
        ),
        migrations.AddField(
            model_name='notification',
            name='term_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.termbooking'),
        ),
    ]
