# Generated by Django 6.0.4 on 2026-08-21 03:47

from django.db import migrations, models


def migrate_no_show_to_completed(apps, schema_editor):
    Booking = apps.get_model('booking', 'Booking')
    Booking.objects.filter(status='no_show').update(status='completed')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_user_student_id'),
    ]

    operations = [
        migrations.RunPython(migrate_no_show_to_completed, noop),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'รอยืนยัน'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('cancelled', 'ยกเลิก'), ('completed', 'เสร็จสิ้น'), ('checked_in', 'เช็คอินแล้ว')], default='pending', max_length=20),
        ),
    ]
