# Generated by Django 6.0.3 on 2026-04-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_options_demandforecast_dynamic_demand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinglog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roomusagestat',
            options={},
        ),
        migrations.RemoveField(
            model_name='roomusagestat',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='roomusagestat',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='roomusagestat',
            name='no_show',
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='availability',
            field=models.CharField(choices=[('likely_available', '🟢 ยังว่าง'), ('recommended', '🟡 ควรจอง'), ('book_soon', '🟠 รีบจอง'), ('book_now', '🔴 ควรจองตอนนี้เลย')], default='likely_available', max_length=20),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='demand_level',
            field=models.CharField(choices=[('low', 'ต่ำ'), ('medium', 'ปานกลาง'), ('high', 'สูง'), ('urgent', 'เร่งด่วน')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='dynamic_demand',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='term_demand',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='roomusagestat',
            name='dynamic_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomusagestat',
            name='term_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='termbooking',
            name='term_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='ชื่อเทอม'),
        ),
    ]
