# Generated by Django 6.0.4 on 2026-09-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_pending', 'รอการอนุมัติ'), ('booking_approved', 'การจองได้รับอนุมัติ'), ('booking_rejected', 'การจองถูกปฏิเสธ'), ('booking_reminder', 'เตือนก่อนใช้งาน'), ('booking_cancelled', 'การจองถูกยกเลิก'), ('term_approved', 'การจองทั้งเทอมได้รับอนุมัติ'), ('demand_alert', 'แจ้งเตือนความต้องการสูง'), ('system', 'ระบบ')], max_length=30),
        ),
    ]
