# Generated by Django 6.0.4 on 2026-09-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_reject_reason_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='termbooking',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='เหตุผลที่ปฏิเสธ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_pending', 'รอการอนุมัติ'), ('booking_approved', 'การจองได้รับอนุมัติ'), ('booking_rejected', 'การจองถูกปฏิเสธ'), ('booking_reminder', 'เตือนก่อนใช้งาน'), ('booking_cancelled', 'การจองถูกยกเลิก'), ('term_pending', 'การจองทั้งเทอมรออนุมัติ'), ('term_approved', 'การจองทั้งเทอมได้รับอนุมัติ'), ('term_rejected', 'การจองทั้งเทอมถูกปฏิเสธ'), ('demand_alert', 'แจ้งเตือนความต้องการสูง'), ('system', 'ระบบ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='termbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'รออนุมัติ'), ('active', 'ใช้งานอยู่'), ('rejected', 'ถูกปฏิเสธ'), ('cancelled', 'ยกเลิกแล้ว'), ('ended', 'หมดเทอมแล้ว')], default='pending', max_length=20),
        ),
    ]
