# Generated by Django 6.0.4 on 2026-10-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_term_booking_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='termbooking',
            name='approved_by',
        ),
    ]
